services:
  - type: web
    name: notes-manager-app
    env: node
    plan: free
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: notes-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
    
databases:
  - name: notes-db
    plan: free
